name: AuroraPlayer
options:
  bundleIdPrefix: com.aurora
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    iOS: 16.0

targets:
  AuroraPlayer:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: AuroraPlayer
        # Aquí NO debe aparecer Info.plist como recurso
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.aurora.player